# fly.toml app configuration file generated for upstat on 2025-02-26T19:16:09+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'upstat'
primary_region = 'sin'

[build]

[processes]
  web = 'uvicorn main:app --bind 0.0.0.0:8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['web']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
