# fly.toml app configuration file generated for upstat on 2025-03-04T20:53:22+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'upstat'
primary_region = 'bom'

[build]
  dockerfile = "Dockerfile.celery"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
