"""marking rid as unique and updating index

Revision ID: b38b092c0665
Revises: 9784acb7fafb
Create Date: 2025-02-19 00:06:17.629881

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b38b092c0665"
down_revision: Union[str, None] = "9784acb7fafb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("events_url_method_frequency_key", "events", type_="unique")
    op.create_unique_constraint(None, "events", ["rid"])
    op.create_unique_constraint(None, "events", ["url", "method", "frequency", "rid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "events", type_="unique")
    op.drop_constraint(None, "events", type_="unique")
    op.create_unique_constraint("events_url_method_frequency_key", "events", ["url", "method", "frequency"])
    # ### end Alembic commands ###
