"""Adding the lastest_events :/

Revision ID: e3f4dc0e020b
Revises: 6a9b17eaf274
Create Date: 2025-02-23 01:06:31.157457

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e3f4dc0e020b"
down_revision: Union[str, None] = "6a9b17eaf274"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "latest_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("eid", sa.Integer(), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("time_took", sa.Numeric(), nullable=False),
        sa.Column("run_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["eid"], ["events.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_last_10_event_runs_eid_run_at", "latest_events", ["eid", "run_at"], unique=False)
    op.create_index(op.f("ix_latest_events_eid"), "latest_events", ["eid"], unique=False)
    # ### end Alembic commands ###

    op.execute(
        """
    CREATE OR REPLACE FUNCTION latest_events_runs()
    RETURNS TRIGGER AS $$
    BEGIN
        -- Insert the new run
        INSERT INTO latest_events (eid, status_code, time_took, run_at)
        VALUES (NEW.eid, NEW.status_code, NEW.time_took, NEW.run_at);
    
        -- Ensure we only keep the last 10 runs
        DELETE FROM latest_events
        WHERE id IN (
            SELECT id FROM latest_events
            WHERE eid = NEW.eid
            ORDER BY run_at DESC OFFSET 10
        );
        RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """
    )

    op.execute(
        """
    CREATE TRIGGER trigger_latest_events_runs
    AFTER INSERT ON event_logs
    FOR EACH ROW
    EXECUTE FUNCTION latest_events_runs();
    """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_latest_events_eid"), table_name="latest_events")
    op.drop_index("idx_latest_events_eid_run_at", table_name="latest_events")
    op.drop_table("latest_events")
    op.execute("""DROP FUNCTION IF EXISTS latest_events_runs;""")
    op.execute("""DROP TRIGGER IF EXISTS trigger_latest_events_runs;""")
    # ### end Alembic commands ###
